/**
 * Unified Comment Types
 * Shared types for comment system used by both Devotion and Plan Sessions
 */

/**
 * Base comment fields shared by all comment types
 */
export interface BaseComment {
  id: string;
  user_id: string;
  parent_comment_id: string | null;
  content: string;
  like_count: number;
  reply_count: number;
  status: 'active' | 'inactive';
  created_at: string;
  updated_at: string;
}

/**
 * Unified comment type that handles both Devotion and Plan Session comments
 * Uses optional fields for context-specific properties
 */
export interface UnifiedComment extends BaseComment {
  /**
   * Context identifier - question_id for Devotion, shared_session_id for Plans
   */
  contextId: string;

  /**
   * Nested replies (if loaded)
   */
  replies?: UnifiedComment[];

  // ============================================================================
  // Plan-specific fields (optional)
  // ============================================================================

  /**
   * Day number in the reading plan (Plan Sessions only)
   */
  day_number?: number;

  // ============================================================================
  // Devotion-specific fields (optional)
  // ============================================================================

  /**
   * Whether this comment was posted anonymously
   */
  is_anonymous?: boolean;

  /**
   * Whether this comment is hidden from AI (Humans Only mode)
   */
  is_humans_only?: boolean;

  /**
   * Whether this comment was generated by AI
   */
  is_ai_generated?: boolean;

  /**
   * AI review status for AI-generated comments
   */
  ai_review_status?: 'pending' | 'read' | 'responded' | null;
}

/**
 * Feature flags for comment components
 * Controls which features are enabled based on context
 */
export interface CommentFeatures {
  /** Show AI indicator badge and disclaimer for AI-generated comments */
  showAiIndicator: boolean;
  /** Show anonymous indicator for anonymous comments */
  showAnonymous: boolean;
  /** Allow editing own comments */
  allowEdit: boolean;
  /** Enable rich text rendering (Bible verse embeds) */
  enableRichText: boolean;
  /** Enable verse detection in input (live preview) */
  enableVerseDetection: boolean;
  /** Show anonymous toggle in input */
  enableAnonymousToggle: boolean;
  /** Show "Humans Only" toggle in input (hides comment from AI) */
  enableHumansOnlyToggle: boolean;
}

/**
 * Comment context value provided by DevotionCommentProvider or PlanCommentProvider
 * Components consume this context instead of directly accessing stores
 */
export interface CommentContextValue {
  // ============================================================================
  // Feature configuration
  // ============================================================================
  features: CommentFeatures;

  // ============================================================================
  // Actions (bound to correct store/service by provider)
  // ============================================================================

  /** Like/unlike a comment */
  onLike: (commentId: string) => void;

  /** Edit a comment (returns success) */
  onEdit: (commentId: string, newContent: string) => Promise<boolean>;

  /** Delete a comment */
  onDelete: (commentId: string) => void;

  /** Submit a new comment (returns success) */
  onSubmitComment: (
    content: string,
    parentCommentId?: string,
    isAnonymous?: boolean,
    isHumansOnly?: boolean
  ) => Promise<boolean>;

  /** Open thread view for a comment */
  onOpenThread: (commentId: string) => void;

  /** Close thread view, return to comments list */
  onCloseThread: () => void;

  /** Fetch replies for a comment (for lazy loading) */
  onFetchReplies: (commentId: string) => Promise<void>;

  /** Set replies on a comment (after fetching) */
  setRepliesForComment: (commentId: string, replies: UnifiedComment[]) => void;

  /** Clear target comment highlight */
  clearTargetHighlight: () => void;

  // ============================================================================
  // State accessors
  // ============================================================================

  /** Check if a comment is liked by current user */
  isCommentLiked: (commentId: string) => boolean;

  /** Get current user ID */
  getCurrentUserId: () => string | undefined;

  /** Check if a user is the current user (author check) */
  isCurrentUser: (userId: string) => boolean;

  /** Get display name for a user */
  getDisplayName: (userId: string) => string;

  // ============================================================================
  // Comment data (read from store via provider)
  // ============================================================================

  /** All comments for current context */
  comments: UnifiedComment[];

  /** Total comment count */
  totalCount: number;

  /** Whether comments are loading */
  isLoading: boolean;

  /** Whether comments have been initialized (first load complete) */
  isInitialized: boolean;

  /** Whether more comments are available (pagination) */
  hasMore: boolean;

  /** Load more comments (pagination) */
  loadMore: () => void;

  /** Whether currently loading more comments */
  isLoadingMore: boolean;

  // ============================================================================
  // Thread state
  // ============================================================================

  /** ID of comment currently open in thread view (null if not in thread mode) */
  activeThreadCommentId: string | null;

  /** Comment being viewed in thread mode */
  threadParentComment: UnifiedComment | null;

  /** Replies for thread parent (filtered active only) */
  threadReplies: UnifiedComment[];

  // ============================================================================
  // Deep-link state
  // ============================================================================

  /** Target comment ID for deep-link navigation */
  targetCommentId: string | null;

  /** Whether target comment should be highlighted */
  targetCommentHighlight: boolean;
}

/**
 * Default feature configuration for Devotion context
 */
export const DEVOTION_FEATURES: CommentFeatures = {
  showAiIndicator: true,
  showAnonymous: true,
  allowEdit: true,
  enableRichText: true,
  enableVerseDetection: true,
  enableAnonymousToggle: true,
  enableHumansOnlyToggle: true,
};

/**
 * Default feature configuration for Plan Sessions context
 */
export const PLAN_SESSION_FEATURES: CommentFeatures = {
  showAiIndicator: false,  // No AI in plan sessions
  showAnonymous: true,
  allowEdit: true,
  enableRichText: true,
  enableVerseDetection: true,
  enableAnonymousToggle: true,
  enableHumansOnlyToggle: true,
};
