/**
 * Plan Service - Supabase operations for Bible Plans
 *
 * Handles:
 * - Plan session CRUD operations (personal and shared)
 * - Participant operations for shared sessions
 * - Comment CRUD and real-time subscriptions
 * - Invite code generation and validation
 *
 * NOTE: shared_sessions table has been consolidated into plan_sessions.
 * A PlanSession with is_shared=true is a shared session.
 */

import { supabase } from '../lib/supabase';
import { planStore$ } from '../state/planStore';
import { userProfileCache$ } from '../state/userProfileCache';
import type {
  PlanSession,
  SessionParticipant,
  PlanSessionInsert,
  SessionParticipantInsert,
  CommentInsert,
  CommentLikeInsert,
  SessionUserReward,
  SessionUserRewardInsert,
  SessionUserStats,
  DayRewardsSummary,
  UserGlobalStats,
} from '../types/database';
import { REWARD_TYPES, REWARD_POINTS, getDailyPlanCompletionMultiplier, getPlanCompletionMultiplier, type RewardType } from '../types/database';
import type { ParticipantWithProfile, SessionCommentWithUser } from '../state/planStore';
import type { RealtimeChannel } from '@supabase/supabase-js';
import NetInfo from '@react-native-community/netinfo';
import { calculatePlanDay } from '../utils/dateFormatters';
import { getPlanDaysCompletedToday, trackPlanDayCompletion, getPlansCompletedToday, trackPlanCompletion } from '../state/gamificationStore';
import { recordActivityOnServer } from './gamificationService';

const PAGE_SIZE = 20;

let realtimeChannel: RealtimeChannel | null = null;
let currentUserId: string | null = null;
// Track current subscription context for day filtering
let currentSubscriptionDay: number | null = null;

// ============================================================================
// PLAN SESSIONS (Personal & Shared Progress)
// ============================================================================

/**
 * Create a new plan session for a user
 */
export async function createPlanSession(
  planId: string,
  userId: string,
  options?: {
    isShared?: boolean;
    sharedName?: string;
    startDay?: number; // Which day to start on (default: 1)
  }
): Promise<PlanSession | null> {
  try {
    const startDay = options?.startDay ?? 1;

    // Calculate started_at so today = startDay
    // If startDay is 5, we set started_at to 4 days ago
    const startedAt = new Date();
    startedAt.setDate(startedAt.getDate() - (startDay - 1));

    const insertData: PlanSessionInsert = {
      plan_id: planId,
      user_id: userId,
      current_day: startDay,
      started_at: startedAt.toISOString(),
      status: 'active',
      is_shared: options?.isShared ?? false,
      shared_name: options?.sharedName ?? null,
      // invite_code is auto-generated by trigger when is_shared=true
    };

    const { data, error } = await supabase
      .from('plan_sessions')
      .insert(insertData)
      .select('*')
      .single();

    if (error) {
      console.error('[PlanService] Error creating plan session:', error);
      throw error;
    }

    return data;
  } catch (error) {
    console.error('[PlanService] createPlanSession error:', error);
    return null;
  }
}

/**
 * Fetch user's own plan sessions (both personal and shared sessions they own)
 */
export async function fetchUserPlanSessions(userId: string): Promise<PlanSession[]> {
  try {
    const { data, error } = await supabase
      .from('plan_sessions')
      .select('*')
      .eq('user_id', userId)
      .neq('status', 'inactive')
      .order('updated_at', { ascending: false });

    if (error) {
      console.error('[PlanService] Error fetching plan sessions:', error);
      throw error;
    }

    return data || [];
  } catch (error) {
    console.error('[PlanService] fetchUserPlanSessions error:', error);
    return [];
  }
}

/**
 * Update plan session progress
 */
export async function updatePlanSessionProgress(
  sessionId: string,
  currentDay: number,
  status?: 'active' | 'paused' | 'completed'
): Promise<boolean> {
  try {
    const updateData: Record<string, unknown> = { current_day: currentDay };
    if (status) {
      updateData.status = status;
      if (status === 'completed') {
        updateData.completed_at = new Date().toISOString();
      }
    }

    const { error } = await supabase
      .from('plan_sessions')
      .update(updateData)
      .eq('id', sessionId);

    if (error) {
      console.error('[PlanService] Error updating plan session:', error);
      throw error;
    }

    return true;
  } catch (error) {
    console.error('[PlanService] updatePlanSessionProgress error:', error);
    return false;
  }
}

// ============================================================================
// SHARED SESSIONS (plan_sessions with is_shared=true)
// ============================================================================

/**
 * Share an existing plan session (converts personal to shared)
 * Invite code is auto-generated by database trigger
 */
export async function sharePlanSession(
  sessionId: string,
  sharedName: string
): Promise<PlanSession | null> {
  try {
    const { data, error } = await supabase
      .from('plan_sessions')
      .update({
        is_shared: true,
        shared_name: sharedName,
      })
      .eq('id', sessionId)
      .select('*')
      .single();

    if (error) {
      console.error('[PlanService] Error sharing plan session:', error);
      throw error;
    }

    // Owner is auto-added as participant by database trigger
    return data;
  } catch (error) {
    console.error('[PlanService] sharePlanSession error:', error);
    return null;
  }
}

/**
 * Create a new shared plan session
 * Invite code is auto-generated by database trigger
 */
export async function createSharedSession(
  planId: string,
  sharedName: string,
  userId: string
): Promise<PlanSession | null> {
  return createPlanSession(planId, userId, {
    isShared: true,
    sharedName,
  });
}

/**
 * Fetch a shared session by invite code
 */
export async function fetchSharedSessionByCode(
  inviteCode: string
): Promise<PlanSession | null> {
  try {
    const { data, error } = await supabase
      .from('plan_sessions')
      .select('*')
      .eq('invite_code', inviteCode.toUpperCase())
      .eq('is_shared', true)
      .eq('status', 'active')
      .single();

    if (error) {
      console.error('[PlanService] Error fetching shared session by code:', error);
      return null;
    }

    return data;
  } catch (error) {
    console.error('[PlanService] fetchSharedSessionByCode error:', error);
    return null;
  }
}

/**
 * Check if user is already a participant of a shared session
 */
export async function checkSessionParticipation(
  planSessionId: string,
  userId: string
): Promise<boolean> {
  try {
    const { data } = await supabase
      .from('session_participants')
      .select('id')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .eq('status', 'active')
      .single();

    return !!data;
  } catch {
    return false;
  }
}

/**
 * Extended shared session with additional display data
 */
export interface SharedSessionWithDetails extends PlanSession {
  participant_count: number;
  owner_display_name?: string;
  owner_avatar_url?: string | null;
}

/**
 * Fetch user's shared sessions (owned or participating) with enriched data
 */
export async function fetchUserSharedSessions(userId: string): Promise<PlanSession[]> {
  try {
    // Get sessions where user is a participant
    const { data: participations, error: partError } = await supabase
      .from('session_participants')
      .select('plan_session_id')
      .eq('user_id', userId)
      .eq('status', 'active');

    if (partError) throw partError;

    if (!participations || participations.length === 0) return [];

    const sessionIds = participations.map(p => p.plan_session_id);

    const { data, error } = await supabase
      .from('plan_sessions')
      .select('*')
      .in('id', sessionIds)
      .eq('is_shared', true)
      .eq('status', 'active')
      .order('updated_at', { ascending: false });

    if (error) throw error;

    return data || [];
  } catch (error) {
    console.error('[PlanService] fetchUserSharedSessions error:', error);
    return [];
  }
}

/**
 * Fetch user's shared sessions with enriched data (participant counts, owner info)
 */
export async function fetchUserSharedSessionsWithDetails(userId: string): Promise<SharedSessionWithDetails[]> {
  try {
    // Get sessions where user is a participant
    const { data: participations, error: partError } = await supabase
      .from('session_participants')
      .select('plan_session_id')
      .eq('user_id', userId)
      .eq('status', 'active');

    if (partError) throw partError;

    if (!participations || participations.length === 0) return [];

    const sessionIds = participations.map(p => p.plan_session_id);

    // Fetch shared plan sessions
    const { data: sessions, error: sessionsError } = await supabase
      .from('plan_sessions')
      .select('*')
      .in('id', sessionIds)
      .eq('is_shared', true)
      .eq('status', 'active')
      .order('updated_at', { ascending: false });

    if (sessionsError) throw sessionsError;
    if (!sessions || sessions.length === 0) return [];

    // Fetch participant counts for all sessions
    const { data: participantCounts, error: countError } = await supabase
      .from('session_participants')
      .select('plan_session_id')
      .in('plan_session_id', sessionIds)
      .eq('status', 'active');

    if (countError) throw countError;

    // Count participants per session
    const countMap = new Map<string, number>();
    (participantCounts || []).forEach(p => {
      const current = countMap.get(p.plan_session_id) || 0;
      countMap.set(p.plan_session_id, current + 1);
    });

    // Fetch owner profiles
    const ownerIds = [...new Set(sessions.map(s => s.user_id))];
    await userProfileCache$.ensureProfiles(ownerIds);

    // Enrich sessions with additional data
    const enrichedSessions: SharedSessionWithDetails[] = sessions.map(session => {
      const ownerProfile = userProfileCache$.getProfile(session.user_id);
      return {
        ...session,
        participant_count: countMap.get(session.id) || 0,
        owner_display_name: ownerProfile?.display_name || undefined,
        owner_avatar_url: ownerProfile?.avatar_url,
      };
    });

    return enrichedSessions;
  } catch (error) {
    console.error('[PlanService] fetchUserSharedSessionsWithDetails error:', error);
    return [];
  }
}

/**
 * Join a shared session by invite code
 */
export async function joinSharedSession(
  inviteCode: string,
  userId: string
): Promise<{ success: boolean; sharedSession?: PlanSession; error?: string }> {
  try {
    // Find the shared session
    const session = await fetchSharedSessionByCode(inviteCode);
    if (!session) {
      return { success: false, error: 'Invalid or expired invite code' };
    }

    // Check if already a participant (including inactive records from previous leave)
    const { data: existing } = await supabase
      .from('session_participants')
      .select('id, status')
      .eq('plan_session_id', session.id)
      .eq('user_id', userId)
      .maybeSingle();

    if (existing) {
      // If already active, nothing to do
      if (existing.status === 'active') {
        return { success: true, sharedSession: session };
      }

      // If inactive (previously left), reactivate the membership
      const { error: updateError } = await supabase
        .from('session_participants')
        .update({ status: 'active' })
        .eq('id', existing.id);

      if (updateError) {
        console.error('[PlanService] Error reactivating session membership:', updateError);
        return { success: false, error: 'Failed to rejoin session' };
      }

      return { success: true, sharedSession: session };
    }

    // New participant - insert record
    const insertData: SessionParticipantInsert = {
      plan_session_id: session.id,
      user_id: userId,
      role: 'member',
      current_day: 1,
      status: 'active',
    };

    const { error } = await supabase
      .from('session_participants')
      .insert(insertData);

    if (error) {
      console.error('[PlanService] Error joining shared session:', error);
      return { success: false, error: 'Failed to join session' };
    }

    return { success: true, sharedSession: session };
  } catch (error) {
    console.error('[PlanService] joinSharedSession error:', error);
    return { success: false, error: 'Failed to join session' };
  }
}

/**
 * Leave a shared session
 */
export async function leaveSharedSession(
  planSessionId: string,
  userId: string
): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('session_participants')
      .update({ status: 'inactive' })
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId);

    if (error) throw error;
    return true;
  } catch (error) {
    console.error('[PlanService] leaveSharedSession error:', error);
    return false;
  }
}

// ============================================================================
// ADMIN MANAGEMENT
// ============================================================================

/**
 * Get user's role in a session
 */
export async function getUserSessionRole(
  planSessionId: string,
  userId: string
): Promise<'owner' | 'admin' | 'member' | null> {
  try {
    const { data, error } = await supabase
      .from('session_participants')
      .select('role')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .eq('status', 'active')
      .single();

    if (error || !data) return null;
    return data.role;
  } catch {
    return null;
  }
}

/**
 * Check if user is owner or admin of a session
 */
export async function isUserSessionAdmin(
  planSessionId: string,
  userId: string
): Promise<boolean> {
  const role = await getUserSessionRole(planSessionId, userId);
  return role === 'owner' || role === 'admin';
}

/**
 * Promote a member to admin (owner only)
 */
export async function promoteToAdmin(
  planSessionId: string,
  targetUserId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const { error } = await supabase
      .from('session_participants')
      .update({ role: 'admin' })
      .eq('plan_session_id', planSessionId)
      .eq('user_id', targetUserId)
      .eq('role', 'member')
      .eq('status', 'active');

    if (error) {
      console.error('[PlanService] promoteToAdmin error:', error);
      return { success: false, error: 'Failed to promote member' };
    }

    return { success: true };
  } catch (error) {
    console.error('[PlanService] promoteToAdmin error:', error);
    return { success: false, error: 'Failed to promote member' };
  }
}

/**
 * Demote an admin to member (owner only)
 */
export async function demoteFromAdmin(
  planSessionId: string,
  targetUserId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const { error } = await supabase
      .from('session_participants')
      .update({ role: 'member' })
      .eq('plan_session_id', planSessionId)
      .eq('user_id', targetUserId)
      .eq('role', 'admin')
      .eq('status', 'active');

    if (error) {
      console.error('[PlanService] demoteFromAdmin error:', error);
      return { success: false, error: 'Failed to demote admin' };
    }

    return { success: true };
  } catch (error) {
    console.error('[PlanService] demoteFromAdmin error:', error);
    return { success: false, error: 'Failed to demote admin' };
  }
}

/**
 * Remove a member from session (admins can remove members, not admins/owner)
 */
export async function removeMember(
  planSessionId: string,
  targetUserId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    // Check target is a member (not admin/owner)
    const targetRole = await getUserSessionRole(planSessionId, targetUserId);
    if (targetRole !== 'member') {
      return { success: false, error: 'Can only remove regular members' };
    }

    const { error } = await supabase
      .from('session_participants')
      .update({ status: 'inactive' })
      .eq('plan_session_id', planSessionId)
      .eq('user_id', targetUserId);

    if (error) {
      console.error('[PlanService] removeMember error:', error);
      return { success: false, error: 'Failed to remove member' };
    }

    return { success: true };
  } catch (error) {
    console.error('[PlanService] removeMember error:', error);
    return { success: false, error: 'Failed to remove member' };
  }
}

/**
 * Transfer session ownership to another participant
 * Uses database function for atomic operation
 */
export async function transferOwnership(
  planSessionId: string,
  newOwnerId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const { data, error } = await supabase.rpc('transfer_session_ownership', {
      session_id: planSessionId,
      new_owner_id: newOwnerId,
    });

    if (error) {
      console.error('[PlanService] transferOwnership error:', error);
      return { success: false, error: 'Failed to transfer ownership' };
    }

    if (!data) {
      return { success: false, error: 'Transfer failed - you may not be the owner' };
    }

    return { success: true };
  } catch (error) {
    console.error('[PlanService] transferOwnership error:', error);
    return { success: false, error: 'Failed to transfer ownership' };
  }
}

/**
 * Delete a plan session (owner only for shared, or owner of personal session)
 */
export async function deleteSession(
  planSessionId: string,
  userId: string
): Promise<{ success: boolean; error?: string }> {
  try {
    console.log('[PlanService] deleteSession called:', { planSessionId, userId });

    // Verify ownership
    const { data: session, error: fetchError } = await supabase
      .from('plan_sessions')
      .select('user_id, is_shared')
      .eq('id', planSessionId)
      .single();

    console.log('[PlanService] Session lookup result:', { session, fetchError });

    if (fetchError || !session) {
      console.error('[PlanService] Session not found:', fetchError);
      return { success: false, error: 'Session not found' };
    }

    if (session.user_id !== userId) {
      console.error('[PlanService] User is not owner:', { sessionOwner: session.user_id, currentUser: userId });
      return { success: false, error: 'Only the owner can delete this session' };
    }

    // Soft delete the session
    const { error } = await supabase
      .from('plan_sessions')
      .update({ status: 'inactive' })
      .eq('id', planSessionId);

    if (error) {
      console.error('[PlanService] deleteSession update error:', error);
      return { success: false, error: error.message || 'Failed to delete session' };
    }

    console.log('[PlanService] Session deleted successfully');

    // If shared, also deactivate all participants
    if (session.is_shared) {
      const { error: partError } = await supabase
        .from('session_participants')
        .update({ status: 'inactive' })
        .eq('plan_session_id', planSessionId);

      if (partError) {
        console.error('[PlanService] Error deactivating participants:', partError);
        // Don't fail the whole operation if this fails
      }
    }

    return { success: true };
  } catch (error) {
    console.error('[PlanService] deleteSession exception:', error);
    return { success: false, error: error instanceof Error ? error.message : 'Failed to delete session' };
  }
}

/**
 * Check if user can leave a session
 * Owner/last admin cannot leave without transferring ownership first
 */
export async function canUserLeaveSession(
  planSessionId: string,
  userId: string
): Promise<{ canLeave: boolean; reason?: string; needsTransfer?: boolean }> {
  try {
    const userRole = await getUserSessionRole(planSessionId, userId);

    if (!userRole) {
      return { canLeave: false, reason: 'Not a participant' };
    }

    // Regular members can always leave
    if (userRole === 'member') {
      return { canLeave: true };
    }

    // Check if there are other admins/owner
    const { data: admins, error } = await supabase
      .from('session_participants')
      .select('user_id, role')
      .eq('plan_session_id', planSessionId)
      .in('role', ['owner', 'admin'])
      .eq('status', 'active');

    if (error) {
      return { canLeave: false, reason: 'Failed to check permissions' };
    }

    const otherAdmins = (admins || []).filter(a => a.user_id !== userId);

    // Owner can leave if there are other admins
    if (userRole === 'owner') {
      if (otherAdmins.length > 0) {
        // There are admins, one will become owner
        return { canLeave: true };
      } else {
        // No other admins, need to transfer
        return {
          canLeave: false,
          reason: 'You must transfer ownership before leaving',
          needsTransfer: true
        };
      }
    }

    // Admin can leave if owner still exists or there are other admins
    if (userRole === 'admin') {
      const hasOwner = otherAdmins.some(a => a.role === 'owner');
      if (hasOwner || otherAdmins.length > 0) {
        return { canLeave: true };
      } else {
        // Last admin, need to assign someone
        return {
          canLeave: false,
          reason: 'You must assign a new admin before leaving',
          needsTransfer: true
        };
      }
    }

    return { canLeave: true };
  } catch (error) {
    console.error('[PlanService] canUserLeaveSession error:', error);
    return { canLeave: false, reason: 'Failed to check permissions' };
  }
}

/**
 * Get non-admin members for transfer ownership selection
 */
export async function getEligibleOwnershipRecipients(
  planSessionId: string,
  excludeUserId: string
): Promise<ParticipantWithProfile[]> {
  try {
    const { data, error } = await supabase
      .from('session_participants')
      .select('*')
      .eq('plan_session_id', planSessionId)
      .eq('status', 'active')
      .neq('user_id', excludeUserId)
      .order('joined_at', { ascending: true });

    if (error) throw error;

    const participants = data || [];

    if (participants.length > 0) {
      const userIds = participants.map(p => p.user_id);
      await userProfileCache$.ensureProfiles(userIds);
    }

    return participants.map(p => {
      const profile = userProfileCache$.getProfile(p.user_id);
      return {
        ...p,
        displayName: profile?.display_name || undefined,
        avatarUrl: profile?.avatar_url,
      };
    });
  } catch (error) {
    console.error('[PlanService] getEligibleOwnershipRecipients error:', error);
    return [];
  }
}

// ============================================================================
// PARTICIPANTS
// ============================================================================

/**
 * Fetch participants for a shared session
 */
export async function fetchSessionParticipants(
  planSessionId: string
): Promise<ParticipantWithProfile[]> {
  try {
    const { data, error } = await supabase
      .from('session_participants')
      .select('*')
      .eq('plan_session_id', planSessionId)
      .eq('status', 'active')
      .order('joined_at', { ascending: true });

    if (error) throw error;

    const participants = data || [];

    // Load user profiles
    if (participants.length > 0) {
      const userIds = participants.map(p => p.user_id);
      await userProfileCache$.ensureProfiles(userIds);
    }

    // Enrich with profile data
    return participants.map(p => {
      const profile = userProfileCache$.getProfile(p.user_id);
      return {
        ...p,
        displayName: profile?.display_name || undefined,
        avatarUrl: profile?.avatar_url,
      };
    });
  } catch (error) {
    console.error('[PlanService] fetchSessionParticipants error:', error);
    return [];
  }
}

/**
 * Update participant progress
 */
export async function updateParticipantProgress(
  planSessionId: string,
  userId: string,
  currentDay: number
): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('session_participants')
      .update({
        current_day: currentDay,
        last_active_at: new Date().toISOString(),
      })
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId);

    if (error) throw error;
    return true;
  } catch (error) {
    console.error('[PlanService] updateParticipantProgress error:', error);
    return false;
  }
}

// ============================================================================
// SESSION COMMENTS
// ============================================================================

/**
 * Fetch comments for a specific day in a shared session
 */
export async function fetchSessionComments(
  planSessionId: string,
  dayNumber: number,
  page: number = 0
): Promise<{ comments: SessionCommentWithUser[]; hasMore: boolean }> {
  try {
    const offset = page * PAGE_SIZE;

    const { data, error, count } = await supabase
      .from('comments')
      .select('*', { count: 'exact' })
      .eq('context_type', 'plan_session')
      .eq('plan_session_id', planSessionId)
      .eq('day_number', dayNumber)
      .is('parent_comment_id', null)
      .eq('status', 'active')
      .order('created_at', { ascending: false })
      .range(offset, offset + PAGE_SIZE - 1);

    if (error) throw error;

    const comments = data || [];

    // Load user profiles
    if (comments.length > 0) {
      const userIds = [...new Set(comments.map(c => c.user_id))];
      await userProfileCache$.ensureProfiles(userIds);
    }

    const hasMore = count ? offset + PAGE_SIZE < count : false;

    return { comments: comments as SessionCommentWithUser[], hasMore };
  } catch (error) {
    console.error('[PlanService] fetchSessionComments error:', error);
    return { comments: [], hasMore: false };
  }
}

/**
 * Fetch replies for a session comment
 */
export async function fetchSessionCommentReplies(
  parentCommentId: string
): Promise<SessionCommentWithUser[]> {
  try {
    const { data, error } = await supabase
      .from('comments')
      .select('*')
      .eq('context_type', 'plan_session')
      .eq('parent_comment_id', parentCommentId)
      .eq('status', 'active')
      .order('created_at', { ascending: true });

    if (error) throw error;

    const replies = data || [];

    if (replies.length > 0) {
      const userIds = [...new Set(replies.map(r => r.user_id))];
      await userProfileCache$.ensureProfiles(userIds);

      // Trigger cache save after replies are fetched for offline access
      const sessionId = planStore$.activeSharedSessionId.get();
      const dayNumber = planStore$.selectedDayNumber.get();
      if (sessionId) {
        // Save asynchronously (non-blocking)
        planStore$.saveSessionCommentsToStorage(sessionId, dayNumber).catch((err: Error) => {
          console.warn('[PlanService] Failed to cache replies:', err.message);
        });
      }
    }

    return replies as SessionCommentWithUser[];
  } catch (error) {
    console.error('[PlanService] fetchSessionCommentReplies error:', error);
    return [];
  }
}

/**
 * Create a session comment
 */
export async function createSessionComment(
  planSessionId: string,
  dayNumber: number,
  content: string,
  userId: string,
  parentCommentId?: string | null,
  isAnonymous?: boolean,
  isHumansOnly?: boolean
): Promise<SessionCommentWithUser | null> {
  try {
    const insertData: CommentInsert = {
      context_type: 'plan_session',
      plan_session_id: planSessionId,
      day_number: dayNumber,
      user_id: userId,
      content: content.trim(),
      parent_comment_id: parentCommentId || null,
      status: 'active',
      is_anonymous: isAnonymous ?? false,
      is_humans_only: isHumansOnly ?? false,
    };

    const { data, error } = await supabase
      .from('comments')
      .insert(insertData)
      .select('*')
      .single();

    if (error) throw error;

    await userProfileCache$.ensureProfiles([userId]);

    return data as SessionCommentWithUser;
  } catch (error) {
    console.error('[PlanService] createSessionComment error:', error);
    return null;
  }
}

/**
 * Delete a session comment (soft delete)
 */
export async function deleteSessionComment(commentId: string): Promise<boolean> {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return false;

    const { error } = await supabase
      .from('comments')
      .update({ status: 'inactive' })
      .eq('id', commentId)
      .eq('user_id', user.id);

    if (error) throw error;
    return true;
  } catch (error) {
    console.error('[PlanService] deleteSessionComment error:', error);
    return false;
  }
}

/**
 * Update a session comment content
 */
export async function updateSessionComment(commentId: string, content: string): Promise<boolean> {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return false;

    const { error } = await supabase
      .from('comments')
      .update({ content, updated_at: new Date().toISOString() })
      .eq('id', commentId)
      .eq('user_id', user.id);

    if (error) throw error;
    return true;
  } catch (error) {
    console.error('[PlanService] updateSessionComment error:', error);
    return false;
  }
}

/**
 * Toggle like on a session comment
 */
export async function toggleSessionCommentLike(
  commentId: string,
  userId: string,
  isCurrentlyLiked: boolean
): Promise<boolean> {
  try {
    if (isCurrentlyLiked) {
      const { error } = await supabase
        .from('comment_likes')
        .delete()
        .eq('comment_id', commentId)
        .eq('user_id', userId);

      if (error) throw error;
    } else {
      const insertData: CommentLikeInsert = {
        comment_id: commentId,
        user_id: userId,
      };

      const { error } = await supabase
        .from('comment_likes')
        .insert(insertData);

      if (error) throw error;
    }

    return true;
  } catch (error) {
    console.error('[PlanService] toggleSessionCommentLike error:', error);
    return false;
  }
}

/**
 * Fetch user's liked comment IDs for a shared session
 */
export async function fetchUserSessionLikes(
  userId: string,
  planSessionId: string
): Promise<string[]> {
  try {
    const { data: comments } = await supabase
      .from('comments')
      .select('id')
      .eq('context_type', 'plan_session')
      .eq('plan_session_id', planSessionId);

    if (!comments || comments.length === 0) return [];

    const commentIds = comments.map(c => c.id);

    const { data: likes, error } = await supabase
      .from('comment_likes')
      .select('comment_id')
      .eq('user_id', userId)
      .in('comment_id', commentIds);

    if (error) throw error;

    return (likes || []).map(l => l.comment_id);
  } catch (error) {
    console.error('[PlanService] fetchUserSessionLikes error:', error);
    return [];
  }
}

// ============================================================================
// REAL-TIME SUBSCRIPTIONS
// ============================================================================

/**
 * Set the current user ID for real-time filtering
 */
export function setCurrentUserId(userId: string | null): void {
  currentUserId = userId;
}

/**
 * Subscribe to real-time updates for a shared session
 * Handles: comments, participants, progress updates
 * @param planSessionId - The session ID to subscribe to
 * @param dayNumber - The day number to filter comments by (prevents cross-day contamination)
 */
export function subscribeToSharedSession(planSessionId: string, dayNumber?: number): () => void {
  // Cleanup existing subscription
  if (realtimeChannel) {
    supabase.removeChannel(realtimeChannel);
    realtimeChannel = null;
  }

  // Track the subscription day context
  currentSubscriptionDay = dayNumber ?? null;

  console.log('[PlanService] Subscribing to shared session:', planSessionId, 'day:', currentSubscriptionDay);

  realtimeChannel = supabase
    .channel(`shared-session-${planSessionId}`)

    // Session comment INSERT (unified comments table with plan_session context)
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'comments',
        filter: `plan_session_id=eq.${planSessionId}`,
      },
      async (payload) => {
        // Only process plan_session context comments
        if (payload.new.context_type !== 'plan_session') return;

        // Only add if it's for the subscription day context (prevents cross-day contamination)
        // Use tracked subscription day instead of store value to avoid race conditions
        if (currentSubscriptionDay !== null && payload.new.day_number !== currentSubscriptionDay) {
          console.log('[PlanService] Ignoring comment for different day:', payload.new.day_number, 'vs subscription day:', currentSubscriptionDay);
          return;
        }

        console.log('[PlanService] New comment:', payload);

        const { data, error } = await supabase
          .from('comments')
          .select('*')
          .eq('id', payload.new.id)
          .single();

        if (!error && data) {
          await userProfileCache$.ensureProfiles([data.user_id]);
          planStore$.addComment(data as SessionCommentWithUser);
        }
      }
    )

    // Session comment UPDATE (unified comments table)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'comments',
        filter: `plan_session_id=eq.${planSessionId}`,
      },
      (payload) => {
        // Only process plan_session context comments
        if (payload.new.context_type !== 'plan_session') return;

        // Only process if it's for the subscription day context
        // Use tracked subscription day instead of store value to avoid race conditions
        if (currentSubscriptionDay !== null && payload.new.day_number !== currentSubscriptionDay) {
          return;
        }

        if (payload.new.status === 'inactive') {
          planStore$.removeComment(payload.new.id);
        } else {
          planStore$.updateComment(payload.new);
        }
      }
    )

    // Participant JOIN
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'session_participants',
        filter: `plan_session_id=eq.${planSessionId}`,
      },
      async (payload) => {
        console.log('[PlanService] Participant joined:', payload);

        const participant = payload.new as SessionParticipant;
        await userProfileCache$.ensureProfiles([participant.user_id]);

        const profile = userProfileCache$.getProfile(participant.user_id);
        const withProfile: ParticipantWithProfile = {
          ...participant,
          displayName: profile?.display_name || undefined,
          avatarUrl: profile?.avatar_url,
        };

        planStore$.addParticipant(withProfile);
      }
    )

    // Participant UPDATE (progress change, status change)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'session_participants',
        filter: `plan_session_id=eq.${planSessionId}`,
      },
      (payload) => {
        console.log('[PlanService] Participant updated:', payload);

        if (payload.new.status === 'inactive') {
          planStore$.removeParticipant(payload.new.id);
        } else {
          // Real-time progress sync
          planStore$.updateParticipantProgress(
            payload.new.user_id,
            payload.new.current_day
          );
        }
      }
    )

    // Comment like INSERT (unified comment_likes table)
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'comment_likes',
      },
      (payload) => {
        const likeData = payload.new as { comment_id: string; user_id: string };
        if (likeData.user_id !== currentUserId) {
          planStore$.updateCommentLikeCount(likeData.comment_id, 1);
        }
      }
    )

    // Comment like DELETE (unified comment_likes table)
    .on(
      'postgres_changes',
      {
        event: 'DELETE',
        schema: 'public',
        table: 'comment_likes',
      },
      (payload) => {
        const likeData = payload.old as { comment_id: string; user_id: string };
        if (likeData.user_id !== currentUserId) {
          planStore$.updateCommentLikeCount(likeData.comment_id, -1);
        }
      }
    )

    .subscribe((status) => {
      console.log('[PlanService] Subscription status:', status);
    });

  return () => {
    if (realtimeChannel) {
      console.log('[PlanService] Unsubscribing from shared session');
      supabase.removeChannel(realtimeChannel);
      realtimeChannel = null;
    }
  };
}

/**
 * Initialize shared session - load participants, comments, set up real-time
 * Uses cache-first strategy for offline support
 */
export async function initializeSharedSession(
  planSessionId: string,
  userId: string,
  dayNumber: number = 1
): Promise<void> {
  console.log('[PlanService] Initializing shared session:', planSessionId);

  setCurrentUserId(userId);
  planStore$.setActiveSharedSession(planSessionId);
  planStore$.setSelectedDay(dayNumber);
  planStore$.participantsLoading.set(true);
  planStore$.commentsLoading.set(true);

  try {
    // CACHE-FIRST: Load cached comments immediately
    const cached = await planStore$.loadSessionCommentsFromStorage(planSessionId, dayNumber);
    if (cached?.comments?.length > 0) {
      console.log('[PlanService] Loading cached comments first:', cached.comments.length);
      // Set comments for this specific day
      const currentCommentsByDay = planStore$.commentsByDay.peek();
      planStore$.commentsByDay.set({ ...currentCommentsByDay, [dayNumber]: cached.comments });
      planStore$.userLikedCommentIds.set(cached.likedIds || []);
      planStore$.commentsInitialized.set(true);
      // User sees cached comments immediately
    }

    // Check network status
    const netState = await NetInfo.fetch();
    const isOnline = netState.isConnected ?? false;

    if (!isOnline) {
      // Offline: Stay with cached data
      console.log('[PlanService] Offline - using cached session data only');
      planStore$.participantsLoading.set(false);
      planStore$.commentsLoading.set(false);
      planStore$.commentsInitialized.set(true);
      return;
    }

    // Online: Load fresh data (background refresh if cache was shown)
    const [participants, commentsResult, likedIds] = await Promise.all([
      fetchSessionParticipants(planSessionId),
      fetchSessionComments(planSessionId, dayNumber, 0),
      fetchUserSessionLikes(userId, planSessionId),
    ]);

    planStore$.setParticipants(participants);
    // Set comments for this specific day
    const currentCommentsByDay = planStore$.commentsByDay.peek();
    planStore$.commentsByDay.set({ ...currentCommentsByDay, [dayNumber]: commentsResult.comments });
    planStore$.commentsHasMore.set(commentsResult.hasMore);
    planStore$.userLikedCommentIds.set(likedIds);

    // Subscribe to real-time updates (only when online)
    // Pass dayNumber to track subscription context
    subscribeToSharedSession(planSessionId, dayNumber);

    // Cache for offline
    await planStore$.saveSessionCommentsToStorage(planSessionId, dayNumber);
  } catch (error) {
    console.error('[PlanService] initializeSharedSession error:', error);
    // On error, keep any cached data that was loaded
  } finally {
    planStore$.participantsLoading.set(false);
    planStore$.commentsLoading.set(false);
    planStore$.commentsInitialized.set(true);
  }
}

/**
 * Load comments for a different day in the same session
 * Uses cache-first strategy for offline support
 *
 * Comments are stored by day number in commentsByDay, so each day's comments
 * are isolated and won't interfere with other days.
 */
export async function loadCommentsForDay(
  planSessionId: string,
  dayNumber: number,
  userId: string
): Promise<void> {
  console.log('[PlanService] loadCommentsForDay:', dayNumber);

  planStore$.commentsLoading.set(true);
  planStore$.commentsInitialized.set(false);

  try {
    // CACHE-FIRST: Load cached comments for this day immediately
    const cached = await planStore$.loadSessionCommentsFromStorage(planSessionId, dayNumber);

    if (cached?.comments?.length > 0) {
      console.log('[PlanService] Loading cached comments for day', dayNumber, ':', cached.comments.length);
      // Set comments for this specific day
      const currentCommentsByDay = planStore$.commentsByDay.peek();
      planStore$.commentsByDay.set({ ...currentCommentsByDay, [dayNumber]: cached.comments });
      planStore$.userLikedCommentIds.set(cached.likedIds || []);
      planStore$.commentsInitialized.set(true);
    }

    // Check network status
    const netState = await NetInfo.fetch();
    const isOnline = netState.isConnected ?? false;

    if (!isOnline) {
      // Offline: Stay with cached data
      console.log('[PlanService] Offline - using cached comments only');
      planStore$.commentsLoading.set(false);
      planStore$.commentsInitialized.set(true);
      return;
    }

    // Online: Load fresh data
    const [commentsResult, likedIds] = await Promise.all([
      fetchSessionComments(planSessionId, dayNumber, 0),
      fetchUserSessionLikes(userId, planSessionId),
    ]);

    // Set comments for this specific day (won't affect other days)
    const currentCommentsByDay = planStore$.commentsByDay.peek();
    planStore$.commentsByDay.set({ ...currentCommentsByDay, [dayNumber]: commentsResult.comments });
    planStore$.commentsHasMore.set(commentsResult.hasMore);
    planStore$.commentsPage.set(0);
    planStore$.userLikedCommentIds.set(likedIds);

    // Cache for offline
    await planStore$.saveSessionCommentsToStorage(planSessionId, dayNumber);
  } catch (error) {
    console.error('[PlanService] loadCommentsForDay error:', error);
    // On error, keep any cached data
  } finally {
    planStore$.commentsLoading.set(false);
    planStore$.commentsInitialized.set(true);
  }
}

/**
 * Load more comments (pagination)
 * Only works when online
 */
export async function loadMoreSessionComments(
  planSessionId: string,
  dayNumber: number
): Promise<void> {
  const currentPage = planStore$.commentsPage.get();
  const hasMore = planStore$.commentsHasMore.get();

  if (!hasMore) return;

  // Check network before fetching more
  const netState = await NetInfo.fetch();
  if (!netState.isConnected) {
    console.log('[PlanService] Offline - cannot load more comments');
    return;
  }

  try {
    const nextPage = currentPage + 1;
    const { comments, hasMore: moreAvailable } = await fetchSessionComments(
      planSessionId,
      dayNumber,
      nextPage
    );

    // Append to the specific day's comments
    const currentCommentsByDay = planStore$.commentsByDay.peek();
    const existingComments = currentCommentsByDay[dayNumber] || [];
    planStore$.commentsByDay.set({
      ...currentCommentsByDay,
      [dayNumber]: [...existingComments, ...comments],
    });
    planStore$.commentsPage.set(nextPage);
    planStore$.commentsHasMore.set(moreAvailable);
  } catch (error) {
    console.error('[PlanService] loadMoreSessionComments error:', error);
  }
}

/**
 * Cleanup - call when leaving shared session view
 */
export function cleanupPlanSubscription(): void {
  if (realtimeChannel) {
    console.log('[PlanService] Cleaning up plan subscription');
    supabase.removeChannel(realtimeChannel);
    realtimeChannel = null;
  }
  currentSubscriptionDay = null;
}

/**
 * Resubscribe for a new day - used when day changes while session is active
 * Updates the subscription context to filter for the new day
 */
export function resubscribeForDay(planSessionId: string, dayNumber: number): void {
  console.log('[PlanService] Resubscribing for day:', dayNumber);
  subscribeToSharedSession(planSessionId, dayNumber);
}

/**
 * Sync plan comments if needed - called on app resume or network reconnect
 * Re-initializes subscription and refreshes comments if subscription was lost
 */
export async function syncPlanCommentsIfNeeded(
  sessionId: string,
  dayNumber: number,
  userId: string
): Promise<void> {
  try {
    const netState = await NetInfo.fetch();
    if (!netState.isConnected) {
      console.log('[PlanService] syncPlanCommentsIfNeeded - offline, skipping');
      return;
    }

    // Re-initialize if subscription lost
    if (!realtimeChannel) {
      console.log('[PlanService] syncPlanCommentsIfNeeded - subscription lost, reinitializing');
      await loadCommentsForDay(sessionId, dayNumber, userId);
      subscribeToSharedSession(sessionId, dayNumber);
    } else {
      // Subscription exists, just refresh the comments
      console.log('[PlanService] syncPlanCommentsIfNeeded - refreshing comments');
      const [commentsResult, likedIds] = await Promise.all([
        fetchSessionComments(sessionId, dayNumber, 0),
        fetchUserSessionLikes(userId, sessionId),
      ]);

      // Set comments for this specific day
      const currentCommentsByDay = planStore$.commentsByDay.peek();
      planStore$.commentsByDay.set({ ...currentCommentsByDay, [dayNumber]: commentsResult.comments });
      planStore$.commentsHasMore.set(commentsResult.hasMore);
      planStore$.commentsPage.set(0);
      planStore$.userLikedCommentIds.set(likedIds);

      // Update cache
      await planStore$.saveSessionCommentsToStorage(sessionId, dayNumber);
    }
  } catch (error) {
    console.error('[PlanService] syncPlanCommentsIfNeeded error:', error);
  }
}

/**
 * Check if real-time subscription is active
 */
export function isPlanSubscriptionActive(): boolean {
  return realtimeChannel !== null;
}

/**
 * Get the current subscription day context
 */
export function getCurrentSubscriptionDay(): number | null {
  return currentSubscriptionDay;
}

// ============================================================================
// REWARDS & GAMIFICATION
// ============================================================================

/**
 * Award a reward to a user in a session
 * Handles duplicate prevention via upsert
 * @param customPoints - Optional custom points (overrides default for reward type)
 * @param isOnTime - Whether this is an on-time completion (for DAY_COMPLETE rewards)
 */
export async function awardReward(
  planSessionId: string,
  userId: string,
  rewardType: RewardType,
  dayNumber?: number,
  referenceId?: string,
  customPoints?: number,
  isOnTime?: boolean
): Promise<SessionUserReward | null> {
  try {
    const points = customPoints !== undefined ? customPoints : (REWARD_POINTS[rewardType] || 0);

    const insertData: SessionUserRewardInsert = {
      plan_session_id: planSessionId,
      user_id: userId,
      reward_type: rewardType,
      day_number: dayNumber ?? null,
      reference_id: referenceId ?? null,
      points,
      is_on_time: isOnTime ?? null,
    };

    // Use upsert to handle duplicates (unique constraint on session+user+type+day)
    const { data, error } = await supabase
      .from('user_rewards')
      .upsert(insertData, {
        onConflict: 'plan_session_id,user_id,reward_type,day_number',
        ignoreDuplicates: true,
      })
      .select('*')
      .single();

    if (error) {
      // Ignore duplicate key errors (already has reward)
      if (error.code === '23505') {
        console.log('[PlanService] Reward already exists:', rewardType, dayNumber);
        return null;
      }
      console.error('[PlanService] Error awarding reward:', error);
      throw error;
    }

    return data;
  } catch (error) {
    console.error('[PlanService] awardReward error:', error);
    return null;
  }
}

/**
 * Remove a reward from a user (for undo functionality)
 */
export async function removeReward(
  planSessionId: string,
  userId: string,
  rewardType: RewardType,
  dayNumber?: number
): Promise<boolean> {
  try {
    let query = supabase
      .from('user_rewards')
      .delete()
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .eq('reward_type', rewardType);

    if (dayNumber !== undefined) {
      query = query.eq('day_number', dayNumber);
    } else {
      query = query.is('day_number', null);
    }

    const { error } = await query;

    if (error) {
      console.error('[PlanService] Error removing reward:', error);
      throw error;
    }

    return true;
  } catch (error) {
    console.error('[PlanService] removeReward error:', error);
    return false;
  }
}

/**
 * Check if a day is unlocked (not in the future)
 */
function isDayUnlocked(startedAt: string, dayNumber: number): boolean {
  const parsedStart = new Date(startedAt);
  // Extract local date at midnight
  const startDate = new Date(
    parsedStart.getFullYear(),
    parsedStart.getMonth(),
    parsedStart.getDate()
  );
  const dayDate = new Date(startDate);
  dayDate.setDate(startDate.getDate() + (dayNumber - 1));

  const today = new Date();
  today.setHours(0, 0, 0, 0);
  dayDate.setHours(0, 0, 0, 0);

  return dayDate <= today;
}

/**
 * Check if a day completion is on-time (not catching up on missed days)
 * On-time: current plan day ≤ dayNumber being completed
 * Catch-up: current plan day > dayNumber (completing a past day)
 *
 * Example:
 * - Plan started Jan 1:
 *   - Jan 1: Complete Day 1 → ON-TIME (plan day 1, completing day 1)
 *   - Jan 5: Complete Day 1 → CATCH-UP (plan day 5, completing day 1)
 *   - Jan 5: Complete Day 5 → ON-TIME (plan day 5, completing day 5)
 */
function isOnTimeCompletion(startedAt: string, dayNumber: number): boolean {
  const start = new Date(startedAt);
  const startLocal = new Date(start.getFullYear(), start.getMonth(), start.getDate());
  const today = new Date();
  const todayLocal = new Date(today.getFullYear(), today.getMonth(), today.getDate());

  const msPerDay = 24 * 60 * 60 * 1000;
  const daysElapsed = Math.floor((todayLocal.getTime() - startLocal.getTime()) / msPerDay);
  const currentPlanDay = 1 + daysElapsed;

  return currentPlanDay <= dayNumber;
}

/**
 * Mark a day as complete (awards day_complete reward)
 * - On-time completions: Awards XP with daily diminishing returns
 * - Catch-up completions: Marks complete but awards 0 XP
 */
export async function markDayComplete(
  planSessionId: string,
  userId: string,
  dayNumber: number,
  startedAt?: string,
  _planMaxDays?: number
): Promise<{ success: boolean; xpAwarded: boolean; pointsAwarded: number; allCompleteBonusXP?: number }> {
  // If startedAt is provided, validate the day is unlocked
  if (startedAt && !isDayUnlocked(startedAt, dayNumber)) {
    console.log('[PlanService] Day not yet unlocked:', dayNumber);
    return { success: false, xpAwarded: false, pointsAwarded: 0 };
  }

  // Check if this is an on-time completion
  const isOnTime = startedAt ? isOnTimeCompletion(startedAt, dayNumber) : true;

  // Get current count for diminishing returns
  const todayCompletions = getPlanDaysCompletedToday();

  // Calculate points based on on-time status and daily multiplier
  let pointsToAward = 0;
  if (isOnTime) {
    const dailyMultiplier = getDailyPlanCompletionMultiplier(todayCompletions);
    pointsToAward = Math.floor(REWARD_POINTS[REWARD_TYPES.DAY_COMPLETE] * dailyMultiplier);
    console.log(`[PlanService] On-time completion: ${pointsToAward} XP (multiplier: ${dailyMultiplier})`);
  } else {
    console.log('[PlanService] Catch-up completion: 0 XP');
  }

  // Award the reward (with is_on_time flag and calculated points)
  const reward = await awardReward(
    planSessionId,
    userId,
    REWARD_TYPES.DAY_COMPLETE,
    dayNumber,
    undefined,
    pointsToAward,
    isOnTime
  );

  if (reward === null) {
    // Reward already exists or error occurred
    return { success: true, xpAwarded: false, pointsAwarded: 0 };
  }

  // Track in local state for diminishing returns (and on-time tracking for daily activity)
  trackPlanDayCompletion(planSessionId, dayNumber, isOnTime);

  // Record plan activity for streak tracking and all-complete bonus check
  // Only for on-time completions (first on-time plan of the day)
  let allCompleteBonusXP = 0;
  if (isOnTime && todayCompletions === 0) {
    const activityResult = await recordActivityOnServer(userId, 'plan', `${planSessionId}_day_${dayNumber}`);
    if (activityResult) {
      allCompleteBonusXP = activityResult.allCompleteBonusXP;
    }
  }

  return { success: true, xpAwarded: pointsToAward > 0, pointsAwarded: pointsToAward, allCompleteBonusXP };
}

/**
 * Unmark a day as complete (removes day_complete reward)
 */
export async function unmarkDayComplete(
  planSessionId: string,
  userId: string,
  dayNumber: number
): Promise<boolean> {
  return removeReward(planSessionId, userId, REWARD_TYPES.DAY_COMPLETE, dayNumber);
}

/**
 * Award comment reward for a day (first comment only)
 */
export async function awardCommentReward(
  planSessionId: string,
  userId: string,
  dayNumber: number,
  commentId: string
): Promise<boolean> {
  const reward = await awardReward(
    planSessionId,
    userId,
    REWARD_TYPES.DAY_COMMENT,
    dayNumber,
    commentId
  );
  return reward !== null;
}

/**
 * Fetch all rewards for a user in a session
 */
export async function fetchUserRewards(
  planSessionId: string,
  userId: string
): Promise<SessionUserReward[]> {
  try {
    const { data, error } = await supabase
      .from('user_rewards')
      .select('*')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .order('created_at', { ascending: true });

    if (error) {
      console.error('[PlanService] Error fetching user rewards:', error);
      throw error;
    }

    return data || [];
  } catch (error) {
    console.error('[PlanService] fetchUserRewards error:', error);
    return [];
  }
}

/**
 * Fetch rewards summary per day (for displaying trophies in session view)
 */
export async function fetchDayRewardsSummary(
  planSessionId: string,
  userId: string
): Promise<DayRewardsSummary[]> {
  try {
    const { data, error } = await supabase
      .from('user_rewards')
      .select('day_number, reward_type')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .not('day_number', 'is', null);

    if (error) {
      console.error('[PlanService] Error fetching day rewards summary:', error);
      throw error;
    }

    // Group by day_number
    const dayMap = new Map<number, DayRewardsSummary>();

    (data || []).forEach((reward) => {
      const dayNum = reward.day_number!;
      if (!dayMap.has(dayNum)) {
        dayMap.set(dayNum, {
          dayNumber: dayNum,
          isComplete: false,
          hasComment: false,
        });
      }
      const summary = dayMap.get(dayNum)!;
      if (reward.reward_type === REWARD_TYPES.DAY_COMPLETE) {
        summary.isComplete = true;
      }
      if (reward.reward_type === REWARD_TYPES.DAY_COMMENT) {
        summary.hasComment = true;
      }
    });

    return Array.from(dayMap.values()).sort((a, b) => a.dayNumber - b.dayNumber);
  } catch (error) {
    console.error('[PlanService] fetchDayRewardsSummary error:', error);
    return [];
  }
}

/**
 * Fetch user stats for a session
 */
export async function fetchUserStats(
  planSessionId: string,
  userId: string
): Promise<SessionUserStats | null> {
  try {
    const { data, error } = await supabase
      .from('session_user_stats')
      .select('*')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .single();

    if (error) {
      // No stats yet is not an error
      if (error.code === 'PGRST116') {
        return null;
      }
      console.error('[PlanService] Error fetching user stats:', error);
      throw error;
    }

    return data;
  } catch (error) {
    console.error('[PlanService] fetchUserStats error:', error);
    return null;
  }
}

/**
 * Fetch a user's global stats (XP/level aggregated across all sessions)
 * @deprecated With local-first XP architecture, use gamificationService.fetchUserGlobalStats
 * for OTHER users only. For current user, use totalXP$/currentLevel$ from gamificationStore.
 */
export async function fetchUserGlobalStats(
  userId: string
): Promise<UserGlobalStats | null> {
  try {
    const { data, error } = await supabase
      .from('user_global_stats')
      .select('*')
      .eq('user_id', userId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        // No stats found - user hasn't earned any rewards yet
        return null;
      }
      console.error('[PlanService] Error fetching global stats:', error);
      throw error;
    }

    return data as UserGlobalStats;
  } catch (error) {
    console.error('[PlanService] fetchUserGlobalStats error:', error);
    return null;
  }
}

/**
 * Fetch stats for all participants in a shared session
 * (for leaderboard / comparison features)
 */
export async function fetchSessionParticipantStats(
  planSessionId: string
): Promise<(SessionUserStats & { displayName?: string; avatarUrl?: string | null })[]> {
  try {
    const { data, error } = await supabase
      .from('session_user_stats')
      .select('*')
      .eq('plan_session_id', planSessionId)
      .order('total_points', { ascending: false });

    if (error) {
      console.error('[PlanService] Error fetching participant stats:', error);
      throw error;
    }

    const stats = data || [];

    // Load user profiles
    if (stats.length > 0) {
      const userIds = stats.map(s => s.user_id);
      await userProfileCache$.ensureProfiles(userIds);
    }

    // Enrich with profile data
    return stats.map(s => {
      const profile = userProfileCache$.getProfile(s.user_id);
      return {
        ...s,
        displayName: profile?.display_name || undefined,
        avatarUrl: profile?.avatar_url,
      };
    });
  } catch (error) {
    console.error('[PlanService] fetchSessionParticipantStats error:', error);
    return [];
  }
}

/**
 * Check and award streak rewards based on consecutive days completed
 */
export async function checkAndAwardStreakRewards(
  planSessionId: string,
  userId: string
): Promise<{
  newStreak?: number;
  streakMilestone?: { type: '7-day' | '30-day' | '365-day'; xp: number; rewardType: RewardType };
}> {
  try {
    // Fetch all completed days
    const { data, error } = await supabase
      .from('user_rewards')
      .select('day_number')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .eq('reward_type', REWARD_TYPES.DAY_COMPLETE)
      .not('day_number', 'is', null)
      .order('day_number', { ascending: true });

    if (error || !data) return {};

    const completedDays = data.map(r => r.day_number!).sort((a, b) => a - b);

    // Calculate current streak (consecutive days ending at the most recent)
    let streak = 0;
    if (completedDays.length > 0) {
      streak = 1;
      for (let i = completedDays.length - 1; i > 0; i--) {
        if (completedDays[i] - completedDays[i - 1] === 1) {
          streak++;
        } else {
          break;
        }
      }
    }

    // Award streak rewards based on current streak
    // Track the highest milestone just reached for toast display
    let streakMilestone: { type: '7-day' | '30-day' | '365-day'; xp: number; rewardType: RewardType } | undefined;

    const streakRewards: { threshold: number; type: RewardType; milestoneType?: '7-day' | '30-day' | '365-day' }[] = [
      { threshold: 3, type: REWARD_TYPES.STREAK_3 },
      { threshold: 7, type: REWARD_TYPES.STREAK_7, milestoneType: '7-day' },
      { threshold: 14, type: REWARD_TYPES.STREAK_14 },
      { threshold: 30, type: REWARD_TYPES.STREAK_30, milestoneType: '30-day' },
      { threshold: 60, type: REWARD_TYPES.STREAK_60 },
      { threshold: 90, type: REWARD_TYPES.STREAK_90 },
      { threshold: 365, type: REWARD_TYPES.STREAK_365, milestoneType: '365-day' },
    ];

    for (const { threshold, type, milestoneType } of streakRewards) {
      if (streak >= threshold) {
        const reward = await awardReward(planSessionId, userId, type);
        // Only set milestone if this reward was just awarded (not already claimed)
        if (reward && milestoneType && streak === threshold) {
          streakMilestone = {
            type: milestoneType,
            xp: REWARD_POINTS[type],
            rewardType: type,
          };
        }
      }
    }

    // Update streak in stats (trigger handles totals, but we update streak manually)
    await supabase
      .from('session_user_stats')
      .upsert({
        plan_session_id: planSessionId,
        user_id: userId,
        current_streak: streak,
        longest_streak: streak, // Will be max'd by trigger
        updated_at: new Date().toISOString(),
      }, {
        onConflict: 'plan_session_id,user_id',
      });

    return {
      newStreak: streak,
      streakMilestone,
    };
  } catch (error) {
    console.error('[PlanService] checkAndAwardStreakRewards error:', error);
    return {};
  }
}

/**
 * Calculate plan completion bonus based on on-time day completions
 * Applies diminishing returns if multiple plans completed recently
 * @returns XP bonus amount (on-time days × PLAN_COMPLETE × multiplier)
 */
export async function calculatePlanCompleteBonus(
  planSessionId: string,
  userId: string
): Promise<{ baseBonus: number; multiplier: number; finalBonus: number }> {
  try {
    // Count only on-time day completions
    const { data, error } = await supabase
      .from('user_rewards')
      .select('day_number')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .eq('reward_type', REWARD_TYPES.DAY_COMPLETE)
      .eq('is_on_time', true);

    if (error) {
      console.error('[PlanService] Error calculating plan bonus:', error);
      return { baseBonus: 0, multiplier: 1, finalBonus: 0 };
    }

    const onTimeDays = data?.length ?? 0;
    const baseBonus = onTimeDays * REWARD_POINTS[REWARD_TYPES.PLAN_COMPLETE];

    // Apply diminishing returns for multiple plan completions
    const plansCompletedToday = getPlansCompletedToday();
    const multiplier = getPlanCompletionMultiplier(plansCompletedToday);
    const finalBonus = Math.floor(baseBonus * multiplier);

    console.log(`[PlanService] Plan completion bonus: ${onTimeDays} on-time days × ${REWARD_POINTS[REWARD_TYPES.PLAN_COMPLETE]} × ${multiplier} = ${finalBonus} XP`);

    return { baseBonus, multiplier, finalBonus };
  } catch (error) {
    console.error('[PlanService] calculatePlanCompleteBonus error:', error);
    return { baseBonus: 0, multiplier: 1, finalBonus: 0 };
  }
}

/**
 * Award plan completion bonus (called when all days are completed)
 * Only on-time day completions count towards the bonus
 * Diminishing returns apply for multiple plan completions
 */
export async function awardPlanCompleteBonus(
  planSessionId: string,
  userId: string
): Promise<{ success: boolean; bonusPoints: number; onTimeDays: number }> {
  try {
    const { finalBonus, baseBonus } = await calculatePlanCompleteBonus(planSessionId, userId);
    const onTimeDays = REWARD_POINTS[REWARD_TYPES.PLAN_COMPLETE] > 0
      ? Math.round(baseBonus / REWARD_POINTS[REWARD_TYPES.PLAN_COMPLETE])
      : 0;

    if (finalBonus <= 0) {
      return { success: true, bonusPoints: 0, onTimeDays: 0 };
    }

    // Award the plan completion reward with calculated bonus
    const reward = await awardReward(
      planSessionId,
      userId,
      REWARD_TYPES.PLAN_COMPLETE,
      undefined,
      undefined,
      finalBonus
    );

    if (reward === null) {
      // Already awarded or error
      return { success: true, bonusPoints: 0, onTimeDays: 0 };
    }

    // Track this plan completion for diminishing returns
    trackPlanCompletion(planSessionId);

    console.log(`[PlanService] Plan complete bonus awarded: ${finalBonus} XP (${onTimeDays} on-time days)`);
    return { success: true, bonusPoints: finalBonus, onTimeDays };
  } catch (error) {
    console.error('[PlanService] awardPlanCompleteBonus error:', error);
    return { success: false, bonusPoints: 0, onTimeDays: 0 };
  }
}

/**
 * Check if a specific day is complete
 */
export async function isDayComplete(
  planSessionId: string,
  userId: string,
  dayNumber: number
): Promise<boolean> {
  try {
    const { data, error } = await supabase
      .from('user_rewards')
      .select('id')
      .eq('plan_session_id', planSessionId)
      .eq('user_id', userId)
      .eq('reward_type', REWARD_TYPES.DAY_COMPLETE)
      .eq('day_number', dayNumber)
      .single();

    if (error) {
      // No record found is not an error
      if (error.code === 'PGRST116') {
        return false;
      }
      throw error;
    }

    return !!data;
  } catch (error) {
    console.error('[PlanService] isDayComplete error:', error);
    return false;
  }
}
