-- Migration: Add AI Kenny comment response support
-- This adds fields to track AI review status and identify AI-generated comments

-- Add AI fields to comments table
ALTER TABLE public.comments
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS ai_review_status TEXT DEFAULT 'pending';

-- Add constraint for ai_review_status values
ALTER TABLE public.comments
ADD CONSTRAINT comments_ai_review_status_check
CHECK (ai_review_status IS NULL OR ai_review_status IN ('pending', 'read', 'responded'));

-- Create partial index for efficient querying of pending comments
CREATE INDEX IF NOT EXISTS idx_comments_ai_review_pending
ON public.comments(ai_review_status, created_at)
WHERE ai_review_status = 'pending' AND status = 'active';

-- Comment on new columns
COMMENT ON COLUMN public.comments.is_ai_generated IS 'True if this comment was generated by AI Kenny';
COMMENT ON COLUMN public.comments.ai_review_status IS 'AI review status: pending (awaiting review), read (reviewed, no response needed), responded (AI replied)';
